"""empty message

Revision ID: 380158a6f06a
Revises: 8b29214b0318
Create Date: 2023-06-02 23:34:54.257589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '380158a6f06a'
down_revision = '8b29214b0318'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rentals', schema=None) as batch_op:
        batch_op.drop_column('payment')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rentals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
