"""empty message

Revision ID: 8bb5e5c21616
Revises: bd3dccaf3ed7
Create Date: 2023-06-01 18:52:44.363223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bb5e5c21616'
down_revision = 'bd3dccaf3ed7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rentals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('book_returned', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rentals', schema=None) as batch_op:
        batch_op.drop_column('book_returned')

    # ### end Alembic commands ###
