"""empty message

Revision ID: bd3dccaf3ed7
Revises: 8c89e2326590
Create Date: 2023-05-31 22:34:19.027766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd3dccaf3ed7'
down_revision = '8c89e2326590'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_rentals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('rental_id', sa.Integer(), nullable=True),
    sa.Column('rent_fee', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['rental_id'], ['rentals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('issue_list', sa.String(length=255), nullable=True))

    with op.batch_alter_table('rentals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_rent_fee', sa.Integer(), nullable=True))
        batch_op.drop_constraint('rentals_book_id_fkey', type_='foreignkey')
        batch_op.drop_column('book_id')
        batch_op.drop_column('rent_fee')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rentals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rent_fee', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('book_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('rentals_book_id_fkey', 'books', ['book_id'], ['id'])
        batch_op.drop_column('total_rent_fee')

    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.drop_column('issue_list')

    op.drop_table('book_rentals')
    # ### end Alembic commands ###
