"""empty message

Revision ID: d88c2cfb1927
Revises: 07f2998a7621
Create Date: 2023-06-03 13:36:01.037345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd88c2cfb1927'
down_revision = '07f2998a7621'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('books_issue_limit', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.drop_column('books_issue_limit')

    # ### end Alembic commands ###
