"""empty message

Revision ID: e45157752d69
Revises: a30e8bb4d27b
Create Date: 2023-05-27 21:01:38.854511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e45157752d69'
down_revision = 'a30e8bb4d27b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book_stock')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_stock',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('book_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name='book_stock_book_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='book_stock_pkey')
    )
    # ### end Alembic commands ###
